insert into user_info (mail,password,name) values ("pedrorupster@gmail.com","abc123456","pedro");

insert into categories (name_categorie) values ("accion");
insert into categories (name_categorie) values ("animacion");
insert into categories (name_categorie) values ("aventuras");
insert into categories (name_categorie) values ("comedia");
insert into categories (name_categorie) values ("documental");
insert into categories (name_categorie) values ("historico");
insert into categories (name_categorie) values ("infantil");
insert into categories (name_categorie) values ("musical");
insert into categories (name_categorie) values ("romance");
insert into categories (name_categorie) values ("sagas");
insert into categories (name_categorie) values ("terror");
insert into categories (name_categorie) values ("thriller");	


insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Dracula",1992,"Gary Oldman, Winona Ryder, Anthony Hopkins, Keanu Reeves, Richard E. Grant, Cary Elwes, Sadie Frost, Tom Waits, Bill Campbell, Monica Bellucci, Jay Robinson","Francis Ford Coppola","En el año 1890, el joven abogado Jonathan Harker viaja a un castillo perdido de Transilvania, donde conoce al conde Drácula, que en 1462 perdió a su amor Elisabeta. El Conde, fascinado por una fotografía de Mina Murray, la novia de Harker, que le recuerda a su Elisabeta, viaja hasta Londres cruzando océanos de tiempo para conocerla. Ya en Inglaterra, intentará conquistar y seducir a Lucy, la mejor amiga de Mina. ","terror","img/categories/dracula.jpg","//www.youtube.com/embed/cFSb5sQ0RTY");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Jungla de cristal",1988,"Bruce Willis, Bonnie Bedelia, Alan Rickman, Alexander Godunov, Reginald Veljohnson, Paul Gleason, William Atherton, Hart Bochner, Robert Davi, Grand L. Bush, Wilhelm von Homburg","John McTiernan","En lo alto de la ciudad de Los Ángeles un grupo armado terrorista se ha apoderado de un edificio tomando a un grupo de personas como rehenes. Sólo un hombre, el policía de Nueva York John McClane (Bruce Willis), ha conseguido escapar del acoso terrorista. McClane está solo y fuera de servicio, pero mantendrá una lucha feroz y agotadora contra los secuestradores. Él es la única esperanza para los rehenes.","accion",,"img/categories/jungla.jpg","//www.youtube.com/embed/QIOX44m8ktc");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("El Padrino",1972,"Marlo Brando , Al Pacino ","Francis Ford Coppola","Años 40. Don Vito Corleone (Marlon Brando) es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York. Tiene cuatro hijos: una chica, Connie (Talia Shire), y tres varones: el impulsivo Sonny (James Caan), el pusilánime Freddie (John Cazale) y Michael (Al Pacino), que no quiere saber nada de los negocios de su padre. Cuando Corleone, siempre aconsejado por su consejero Tom Hagen (Robert Duvall), se niega a intervenir en el negocio de las drogas, el jefe de otra banda ordena su asesinato. Empieza entonces una violenta y cruenta guerra entre las familias mafiosas.","accion","img/categories/padrino.jpg","//www.youtube.com/embed/COQvkUmN6H8");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Ocho Apellidos Vascos",2013,"Dani Rovira, Clara Lago, Carmen Machi, Karra Elejalde, Alfonso Sánchez, Alberto López, Aitor Mazo, Lander Otaola","Emilio Martínez-Lázaro","Rafa (Dani Rovira) es un joven señorito andaluz que no ha tenido que salir jamás de su Sevilla natal para conseguir lo único que le importa en la vida: el fino, la gomina, el Betis y las mujeres. Todo cambia cuando conoce a la primera mujer que se resiste a sus encantos: es Amaia (Clara Lago), una chica vasca. Decidido a conquistarla, se traslada a un pueblo de las Vascongadas, donde se hace pasar por vasco para vencer su resistencia. Adopta el nombre de Antxon y varios apellidos vascos: Arguiñano, Igartiburu, Erentxun, Gabilondo, Urdangarín, Otegi, Zubizarreta e incluso Clemente.","comedia","img/categories/ocho.jpg","//www.youtube.com/embed/coevNsXyfXQ");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("La Lista de Schindler",1993,"Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall, Jonathan Sagall, Embeth Davidtz, Norbert Weisser, Martin S. Bergmann, Mark Ivanir, Malgorzata Gebel, Shmuel Levy, Michael Schneider, Joachim Paul Assböck, Branko Lustig, Götz Otto","Steven Spielberg","Segunda Guerra Mundial (1939-1945). Oskar Schindler (Liam Neeson), un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes (1939), consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente (Ben Kingsley), también judío, es el verdadero director en la sombra, pues Schindler carece completamente de conocimientos para dirigir una empresa.","historico","img/categories/lista.jpg","//www.youtube.com/embed/wsIQIPmiAuc");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Pulp Fiction",1994,"John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Eric Stoltz, Tim Roth, Maria de Medeiros, Amanda Plummer, Ving Rhames, Rosanna Arquette, Christopher Walken, Quentin Tarantino, Peter Greene, Phil LaMarr, Paul Calderon, Burr Steers, Frank Whaley, Steve Buscemi","Quentin Tarantino","Jules y Vincent son dos asesinos a sueldo con muy pocas luces que trabajan para Marsellus Wallace. Antes de realizar un trabajo, Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe, pero llega la hora de trabajar y ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.","thriller","img/categories/pulp.jpg","//www.youtube.com/embed/s7EdQ4FqbhY");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Ciudad de Dios",2002,"Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva, Seu Jorge, Jonathan Haagensen, Matheus Nachtergaele, Jefechander Suplino, Alice Braga, Emerson Gomes, Luis Otávio, Babu Santana, Gero Camilo","Fernando Meirelles, Kátia Lund","Basada en hechos reales, este es relato del incremento del crimen organizado en Cidade de Deus, un suburbio de Río de Janeiro, desde finales de los años sesenta hasta el comienzo de los ochenta, cuando el tráfico de drogas y la violencia impusieron su ley en las favelas. Todo comienza a finales de los sesenta, cuando Buscapé tiene 11 años y es sólo un niño más en Cidade de Deus. Tímido y delicado, observa a los niños duros de su barrio, sus robos, sus peleas, sus enfrentamientos diarios con la policía. Ya sabe lo que quiere ser si consigue sobrevivir: fotógrafo. Dadinho, un niño de su misma edad, se traslada al barrio. Sueña con ser el criminal más peligroso de Río de Janeiro y empieza su aprendizaje haciendo recados para los delincuentes locales. Admira a Cabeleira y su pandilla, que se dedica a atracar los camiones del gas y hacen otros pequeños robos armados. Un día Cabeleira da a Dadinho la oportunidad de cometer su primer asesinato...","drama","img/categories/ciudad.jpg","//www.youtube.com/embed/NmkwG7ux3l0");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Bowling For Columbine",2002,"Documentary","Michael Moore","Famoso documental que aborda la cuestión de la violencia en América. ¿Por qué 11.000 personas mueren cada año en Estados Unidos víctimas de las armas de fuego? Los bustos parlantes vociferan desde la pantalla de TV echándole la culpa ya a Satán ya a los videojuegos. Pero, ¿en qué se diferencia Estados Unidos de otros países? ¿Por qué Estados Unidos se ha convertido en responsable y víctima de tanta violencia? Bowling for Columbine no es una película sobre el control de la venta de armas, es una película sobre el miedo de 280 millones de norteamericanos que se sienten más seguros sabiendo que la tenencia de armas es un derecho consagrado por la Constitución. En este incisivo y tragicómico estudio de la violencia y su relación con las armas de fuego aparecen personalidades como Charlon Heston, George W. Bush o Marilyn Manson. Ganó numerosos premios en USA al mejor documental -entre los que destacan los prestigiosos National Board Of Review y el Chicago Film Critics Awards-, así como el premio a la mejor película extranjera -compitiendo con largometrajes- en los César de la Academia Francesa de Cine.","documental","img/categories/bowling.jpg","//www.youtube.com/embed/hH0mSAjp_Jw");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Los Miserables",2012,"Hugh Jackman, Russell Crowe, Anne Hathaway, Amanda Seyfried, Eddie Redmayne, Samantha Barks, Helena Bonham Carter, Sacha Baron Cohen, Aaron Tveit, Isabelle Allen, Daniel Huttlestone, Colm Wilkinson, Natalya Wallace, Michael Jibson, Bertie Carvel, Tim Downie, Marc Pickering, Patrick Godfrey, Killian Donnelly, Fra Fee, Gabriel Vick, George Blagden, Alistair Brammer, Charlotte Hope","Tom Hooper","El expresidiario Jean Valjean (Hugh Jackman) es perseguido durante décadas por el despiadado policía Javert (Russell Crowe). Cuando Valjean decide hacerse cargo de Cosette, la pequeña hija de Fantine (Anne Hathaway), sus vidas cambiarán para siempre. Adaptación cinematográfica del famoso musical 'Les miserables', basado a su vez en la novela homónima de Victor Hugo.","musical","img/categories/miserables.jpg","//www.youtube.com/embed/UVTMU1ZWHHM");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Resacon en las Vegas",2009,"Bradley Cooper, Ed Helms, Zach Galifianakis, Justin Bartha, Heather Graham, Sasha Barrese, Jeffrey Tambor, Ken Jeong, Rachael Harris, Mike Tyson, Mike Epps, Jernard Burks, Rob Riggle, Cleo King, Bryan Callen, Ian Anthony Dale, Gillian Vigman, Todd Phillips, Matt Walsh","Todd Phillips","Historia de una desmadrada despedida de soltero en la que el novio y tres amigos se montan una gran juerga en Las Vegas. Como era de esperar, a la mañana siguiente tienen una resaca tan monumental que no pueden recordar nada de lo ocurrido la noche anterior. Lo más extraordinario es que el novio ha desaparecido y en la suite del hotel se encuentran un tigre y un bebé.","comedia","img/categories/resacon.jpg","//www.youtube.com/embed/_esKPsFVjsg");
insert into movies (movie_name,movie_year,actors,director,sinopsis,movie_category,imagen,trailer)values("Batman Begins",2005,"Christian Bale, Liam Neeson, Katie Holmes, Cillian Murphy, Michael Caine, Morgan Freeman, Gary Oldman, Ken Watanabe, Tom Wilkinson, Rutger Hauer, Mark Boone Junior, Gus Lewis, Linus Roache, Colin McFarlane, Rade Serbedzija, Richard Brake, Christine Adams, Larry Holden, Jack Gleeson","Christopher Nolan","Nueva adaptación del famoso cómic. Narra los orígenes de la leyenda de Batman y los motivos que lo convirtieron en el representante del Bien en la ciudad de Gotham. Bruce Wayne vive obsesionado con el recuerdo de sus padres, muertos a tiros en su presencia. Atormentado por el dolor, se va de Gotham y recorre el mundo hasta que encuentra a un extraño personaje que lo adiestra en todas las disciplinas físicas y mentales que le servirán para combatir el Mal. Por esta razón, la Liga de las Sombras, una poderosa y subversiva sociedad secreta, dirigida por el enigmático Ra's Al Ghul, intenta reclutarlo. Cuando Bruce vuelve a Gotham, la ciudad está dominada por el crimen y la corrupción. Con la ayuda de su leal mayordomo Alfred, del detective de la policía Jim Gordon y de Lucius Fox, su aliado en la sociedad Ciencias Aplicadas de Wayne Enterprises, Wayne libera a su imponente alter ego: Batman, un justiciero enmascarado que utiliza la fuerza, la inteligencia y un despliegue de artefactos de alta tecnología para luchar contra las siniestras fuerzas que amenazan con destruir la ciudad. ","sagas","img/categories/batman.jpg","//www.youtube.com/embed/7zdFsoUF-Fg");



insert into user_movies(user_mail,user_movies)values ("pedrorupster@gmail.com",1);

//CONSULTA PARA VER TODAS LAS PELICULAS QUE TIENE UN USUARIO EN CONCRETO//

	select m.movie_name ,m.movie_id,u.user_movies,u.user_mail from movies m , user_movies u where m.movie_id=u.user_movies and u.user_mail = 'pedrorupster@gmail.com';

//CONSULTA PARA VER UNA PELICULA  POR ACTOR //

	select *from movies where actors like '%willis%';

//CONSULTA PARA VER LAS PELICULAS POR GENERO//

	select *from movies where movie_category ='terror';

//CONSULTA PARA VER LAS PELICULAS POR AÑO//

	select * from movies where movie_year ='1992';

//CONSULTA PARA VER LA NOTA  DE UNA PELICULA//

	select score from movies where movie_name='Los Juegos Del Hambre';


//CONSULTA PARA VER LA NOTA MEDIA DE LAS PELICULAS EN GENERAL DE UN USUARIO EN CONCRETO//

select avg(m.score), m.movie_name ,m.movie_id,u.user_movies,u.user_mail from movies m , user_movies u where m.movie_id=u.user_movies and u.user_mail = 'pedrorupster@gmail.com';


//CONSULTA PARA VER LA NOTA  DE ALGUNA PELICULA EN PARTICULAR DE UN USUARIO CONCRETO//

select m.score, m.movie_name ,m.movie_id,u.user_movies,u.user_mail from movies m , user_movies u where m.movie_id=u.user_movies and u.user_mail = 'pedrorupster@gmail.com' and m.movie_name='Los Juegos Del Hambre';